name: 'Markdown to PDF'

description: 'Converts Markdown to PDF using Pandoc'

inputs:
  list-md-files:
      description: 'TXT files contain md files to convert'
      required: true
  pdf-folder-name:
    description: 'Folder to store the generated PDF files'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
