name: 'Markdown to PDF'

description: 'Converts Markdown to PDF using Pandoc'

inputs:
  md-file-paths:
    description: 'Folder containing Markdown files'
    required: true

  pdf-result-folder:
    description: 'Folder to store the generated PDF files'
    required: true

runs:
  using: "composite"
  steps:

    - name: Create folder for PDF files
      shell: bash
      run: mkdir "${{ inputs.pdf-result-folder }}"

    - name: Install Pandoc & texlive-xetex
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex

    - name: Convert MD to PDF
      shell: bash
      run: |
        while IFS= read -r md_file; do
          echo "converting $md_file to ${{ inputs.pdf-result-folder }}/${pdf_file%.md}.pdf"
          pdf_file=$(echo "$md_file" | sed 's/\//_/g')
          pandoc "$md_file" -s -o "${{ inputs.pdf-result-folder }}/${pdf_file%.md}.pdf"
        done < ${{ inputs.md-file-paths }}