name: 'Markdown to PDF'

description: 'Converts Markdown to PDF using Pandoc'

inputs:
  md_file:
    description: 'Input Markdown file'
    required: true
  pdf_file:
    description: 'Input PDF file'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
