name: Convert MD to PDF

on:
  push:
    branches:
      - 'main'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert to PDF
        uses: ./.github/actions/md-to-pdf
        with:
          md_file: 'input.md'
          pdf_file: 'output.pdf'

      - name: Archive PDF
        uses: actions/upload-artifact@v4
        with:
          name: output-pdf
          path: output.pdf
