name: Convert MD to PDF

on:
  push:
    branches:
      - 'main'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Convert to PDF
        uses: ./.github/actions/md-to-pdf
        with:
          md_file: 'input.md'
          pdf_file: 'output.pdf'
        working-directory: /github/workspace

      - name: Archive PDF
        uses: actions/upload-artifact@v2
        with:
          name: output-pdf
          path: /github/workspace/output.pdf
