name: Convert MD to PDF

on:
  push:
    branches:
      - 'main'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Committed Markdown Files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' > changed_md_files.txt
          cat changed_md_files.txt

      - name: Create folder for PDF files
        run: mkdir pdf_folder

      - name: Install Pandoc & texlive-xetex
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert MD to PDF
        run: |
          while IFS= read -r md_file; do
            echo "converting $md_file"
            pdf_file=$(basename "$md_file_path")
            pandoc "$md_file" -s -o "pdf_folder/${pdf_file%.md}.pdf"
          done < changed_md_files.txt
      
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: output-pdf
          path: pdf_folder