name: Convert MD to PDF

on:
  push:
    branches:
      - 'main'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Committed Markdown Files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' > md_file_list.txt
          cat md_file_list.txt
      
      - name: Checkout code
        uses: ./.github/actions/md-to-pdf
        with:
          pdf-folder-name: pdf_folder
      
      # - name: Upload PDF
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: output-pdf
      #     path: pdf_folder