name: Convert MD to PDF

on:
  push:
    branches:
      - 'main'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Identify changed MD files
        id: changed-md-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$')
          echo "::set-output name=changed_md_files::$CHANGED_FILES"

      # - name: Create folder for PDF files
      #   run: mkdir pdf_folder

      # - name: Install Pandoc & texlive-xetex
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y pandoc texlive-xetex

      # - name: Convert MD to PDF
      #   run: |
      #     for file in ${{ steps.changed-md-files.outputs.changed_md_files }}; do
      #       pandoc "$file" -s -o "pdf_folder/${file%.md}.pdf"
      #     done
      
      # - name: Archive PDF
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: output-pdf
      #     path: pdf_folder


#   convert:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: List changed files
#         id: list_changes
#         run: |
#           echo "Changed files:"
#           $(find . -name "*.md") > changed_files.txt
#           cat changed_files.txt
    
#       - name: Copy changed files
#         run: |
#           while IFS= read -r file; do
#             cp "$file" md_folder/
#           done < changed_files.txt

#       - name: Convert to PDF
#         uses: ./.github/actions/md-to-pdf
#         with:
#           md_folder: 'md_folder'
#           pdf_folder: 'pdf_folder'
