name: Convert MD to PDF

on:
  push:
    branches:
      - 'main'

jobs:
  convert-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List Committed Markdown Files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.md$' > md-file-paths.txt
          cat md-file-paths.txt
      
      - name: Convert md to pdf
        uses: ./.github/actions/md-to-pdf
        with:
          md-file-paths: md-file-paths.txt
          pdf-result-folder: pdf_folder
      
      # - name: Upload PDF
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: output-pdf
      #     path: pdf_folder